alias DreadnoughtHangar.{Repo, Perk}

Repo.insert!(%Perk{name: ~s(Module Recycler  1N!), description: ~s(You don't mind that I overclocked the ship's modules, right? I mean, it's not like they've caught on fire.), slot: ~s(Communications Officer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Reduces module cooldowns when you destroy an enemy by using a module. - Module cooldowns -15 seconds), effect: ~s(Reduces module cooldowns when you destroy an enemy by using a module. - Module cooldowns -15 seconds), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Retaliator  0N!), description: ~s(Just  need  a  little  more  fuel,  better  thermodynamics  and  carrots.  Or  just  carrots.  Good  eyesight  is  everything.), slot: ~s(Communications Officer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Reduces module cooldowns by a small amount when your shield takes damage. - Reduces module cooldowns), effect: ~s(Reduces module cooldowns by a small amount when your shield takes damage. - Reduces module cooldowns), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Desperate Measures "0N!), description: ~s(NO! Not the red button!" GC /game/generic/ui/perks/ui_perk_communication.UI_perk_communication #:/$0<!), slot: ~s(Communications Officer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Removes debuffs, refills energy and resets module cooldowns the first time your health gets low. - Removes debuffs, refills energy, resets module cooldowns), effect: ~s(Removes debuffs, refills energy and resets module cooldowns the first time your health gets low. - Removes debuffs, refills energy, resets module cooldowns), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Feedback Loop #2N!), description: ~s(Those crazy module modifications he made? Well, thing is they work. Sometimes." GC /game/generic/ui/perks/ui_perk_communication.UI_perk_communication $1&  2<!), slot: ~s(Communications Officer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Using a module has a chance of refilling your energy. - Refills energy), effect: ~s(Using a module has a chance of refilling your energy. - Refills energy), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(It's a trap! "1F!), description: ~s(My secret to working with reactors? Swift kick to the core." C? /game/generic/ui/perks/ui_perk_engineering.UI_perk_engineering #0%1<!), slot: ~s(Chief Engineer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Gain a small amount of energy when taking damage from behind. - Gain energy), effect: ~s(Gain a small amount of energy when taking damage from behind. - Gain energy), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Adrenaline Shot "1F!), description: ~s(There go the cooling rods. Thanks to the hull damage, there's plenty of ventilation." C? /game/generic/ui/perks/ui_perk_engineering.UI_perk_engineering #0%1<!), slot: ~s(Chief Engineer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Gain a small amount of energy when you are healed and when healing others. - Gain energy), effect: ~s(Gain a small amount of energy when you are healed and when healing others. - Gain energy), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Tip the scales  .F!), description: ~s(Screw it. If no one's going to save this ship, I will." C? /game/generic/ui/perks/ui_perk_engineering.UI_perk_engineering !-".<!), slot: ~s(Chief Engineer Perk), type: ~s(Passive), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Boosts health regeneration but reduces energy regeneration. - Boosts health regeneration, reduces energy regeneration), effect: ~s(Boosts health regeneration but reduces energy regeneration. - Boosts health regeneration, reduces energy regeneration), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Mr. Fixit  1F!), description: ~s(Give me some power and maybe I can pull off a miracle." C? /game/generic/ui/perks/ui_perk_engineering.UI_perk_engineering !0#1<!), slot: ~s(Chief Engineer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Health regeneration is boosted when energy is set to "off". - Gain 200 HP/s), effect: ~s(Health regeneration is boosted when energy is set to "off". - Gain 200 HP/s), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Slow and Steady  0J!), description: ~s(Think of it this way: a live turtle is better than a dead hare." A= /game/generic/ui/perks/ui_perk_navigation.UI_perk_navigation !u/"0<!), slot: ~s(Navigation Officer Perk), type: ~s(Passive), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Increases damage resistance but decreases movement speed. - Damage resistance +15%, Movement speed -10%), effect: ~s(Increases damage resistance but decreases movement speed. - Damage resistance +15%, Movement speed -10%), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Navigation Expert  0J!), description: ~s(You're fueling the reactor with WHAT?" A= /game/generic/ui/perks/ui_perk_navigation.UI_perk_navigation !/"0<!), slot: ~s(Navigation Officer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(-50% energy consumption), effect: ~s(-50% energy consumption), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Engine Rigger "0J!), description: ~s(What do you mean the reactor is overheating?" A= /game/generic/ui/perks/ui_perk_navigation.UI_perk_navigation #A/$0<!), slot: ~s(Navigation Officer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Energy diverted to engines boosts speed even more, but burns energy at a faster rate. - Movement speed +100%, energy consumption +75%), effect: ~s(Energy diverted to engines boosts speed even more, but burns energy at a faster rate. - Movement speed +100%, energy consumption +75%), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Nerves of Steel  0J!), description: ~s(Quit whining. I think you getting motion sick and us staying alive is a fair exchange." A= /game/generic/ui/perks/ui_perk_navigation.UI_perk_navigation !Q/"0<!), slot: ~s(Navigation Officer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Damage taken while energy is diverted to engines is slightly reduced and gives a short speed boost. - Boosts speed when hit, damage taken reduced by a small amount), effect: ~s(Damage taken while energy is diverted to engines is slightly reduced and gives a short speed boost. - Boosts speed when hit, damage taken reduced by a small amount), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Module Amper  0G!), description: ~s(The circuitry we use to amplify our weapons? Yeah, now it works for modules too." ;7 /game/generic/ui/perks/ui_perk_weapons.UI_perk_weapons !&/"0<!), slot: ~s(Weapons Officer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Increases module damage when energy is diverted to weapons. - Module damage +30%), effect: ~s(Increases module damage when energy is diverted to weapons. - Module damage +30%), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Glass Cannon "0G!), description: ~s(Greatest gun chief I've ever seen. Too bad he has the nerves of a chipmunk." ;7 /game/generic/ui/perks/ui_perk_weapons.UI_perk_weapons #/$0<!), slot: ~s(Weapons Officer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Weapon damage +25%), effect: ~s(Weapon damage +25%), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Destruction Cascade "1G!), description: ~s(I don't know what happened. I just black out sometimes." ;7 /game/generic/ui/perks/ui_perk_weapons.UI_perk_weapons #0%1<!), slot: ~s(Weapons Officer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Weapon damage +30%), effect: ~s(Weapon damage +30%), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})

Repo.insert!(%Perk{name: ~s(Survival Instinct  0G!), description: ~s(Forget about the damn shields. It's do or die." ;7 /game/generic/ui/perks/ui_perk_weapons.UI_perk_weapons !-"0<!), slot: ~s(Weapons Officer Perk), type: ~s(Active), unlock_level: 1337, cr: 1337, sp: 1337, trigger: ~s(Weapons reload faster when you have less than half your health left. - Reload time -50%), effect: ~s(Weapons reload faster when you have less than half your health left. - Reload time -50%), icon_uri: ~s(https://dreadnoughthangar.com/images/weapons/Ballistic%20Cannons.svg), raw_json: %{:placeholder => true}})