alias DreadnoughtHangar.{Repo, Weapon}

Repo.insert!(%Weapon{name: ~s(Ballistic Cannons QrA!), description: ~s(X Ballistic Cannons offer moderate rates of fire and damage against medium range targets. D51 /Game/Generic/UI/weapons/UI_weapon_0.UI_weapon_0 SqT+,Lr8!), slot: ~s(Primary Weapon), usable_by: ~s(Destroyer), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Autocannon Turrets V|A!), description: ~s(o Autocannon Turrets are optimized for medium range encounters and come with a rate of fire and moderate damage. H73 /Game/Generic/UI/weapons/UI_weapon_17.UI_weapon_17 X{Y+,P|8!), slot: ~s(Primary Weapon), usable_by: ~s(Destroyer), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Repeater Turrets NpA!), description: ~s(` Repeater Turrets fire streams of high energy particles, dealing high damage at moderate ranges. @73 /Game/Generic/UI/weapons/UI_weapon_23.UI_weapon_23 PoQ), slot: ~s(Primary Weapon), usable_by: ~s(Destroyer), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Light Particle Turrets BZC!), description: ~s(h Light Particle Turrets feature high accuracy and a long range, but their damage output remains limited. 573 /Game/Generic/UI/weapons/UI_weapon_16.UI_weapon_16 DYE"#<Z8!), slot: ~s(Secondary Weapon), usable_by: ~s(Destroyer), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Rocket Turrets GrC!), description: ~s(^ Rocket Turrets fire volleys of light rockets to mid to close ranges, dealing moderate damage. 973 /Game/Generic/UI/weapons/UI_weapon_24.UI_weapon_24 IqJ&'@r8!), slot: ~s(Secondary Weapon), usable_by: ~s(Destroyer), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Flak Turrets E_C!), description: ~s(r Flak Turrets excel in close range suppression duty, firing high explosive shells that deal area of effect damage. 573 /Game/Generic/UI/weapons/UI_weapon_27.UI_weapon_27 G^H"#<_8!), slot: ~s(Secondary Weapon), usable_by: ~s(Destroyer), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Heavy Ballistic Cannons FcA!), description: ~s(j Heavy Ballistic Cannons feature fast rates of fire and medium damage output at short to medium distances. 651 /Game/Generic/UI/weapons/UI_weapon_6.UI_weapon_6 HbI"#Ac8!), slot: ~s(Primary Weapon), usable_by: ~s(Dreadnought), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Plasma Cannons HbA!), description: ~s(h Plasma Cannons offer moderate rates of fire and damage, and are best used at short to medium distances. 973 /Game/Generic/UI/weapons/UI_weapon_20.UI_weapon_20 JaK$%Cb8!), slot: ~s(Primary Weapon), usable_by: ~s(Dreadnought), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Heavy Plasma Cannons B[A!), description: ~s(l Heavy Plasma Cannons have a very slow rate of fire, but are capable of dealing heavy damage to targets hit. 573 /Game/Generic/UI/weapons/UI_weapon_11.UI_weapon_11 DZE!"=[8!), slot: ~s(Primary Weapon), usable_by: ~s(Dreadnought), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Heavy Mortar Turrets C_C!), description: ~s(x Heavy Mortar Turrets are designed for long range suppression and area denial, featuring high damage but low fire rates. 351 /Game/Generic/UI/weapons/UI_weapon_9.UI_weapon_9 E^F!";_8!), slot: ~s(Secondary Weapon), usable_by: ~s(Dreadnought), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Repeater Guns FcC!), description: ~s(T Repeater Guns offer moderate rates of fire and damage against medium range targets. 773 /Game/Generic/UI/weapons/UI_weapon_22.UI_weapon_22 HbI#$?c8!), slot: ~s(Secondary Weapon), usable_by: ~s(Dreadnought), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Heavy Flak Turrets E_C!), description: ~s(u Heavy Flak Turrets unleash high explosive shells at high rates of fire and are excellent for engaging close targets. 551 /Game/Generic/UI/weapons/UI_weapon_8.UI_weapon_8 G^H!"=_8!), slot: ~s(Secondary Weapon), usable_by: ~s(Dreadnought), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Dual Scatter Cannons FbA!), description: ~s(r Dual Scatter Cannons deal massive damage at short range, but their efficiency deteriorates rapidly with distance. 451 /Game/Generic/UI/weapons/UI_weapon_5.UI_weapon_5 HaI!">b8!), slot: ~s(Primary Weapon), usable_by: ~s(Corvette), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Dual Heavy Autocannons DbA!), description: ~s(Z Dual Heavy Autocannons offer a high rate of fire and moderate damage at medium distances. 473 /Game/Generic/UI/weapons/UI_weapon_26.UI_weapon_26 FaG"#>b8!), slot: ~s(Primary Weapon), usable_by: ~s(Corvette), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Dual Repeaters D_A!), description: ~s(B Dual Repeaters offer good accuracy and damage at moderate ranges. 451 /Game/Generic/UI/weapons/UI_weapon_4.UI_weapon_4 F^G  !>_8!), slot: ~s(Primary Weapon), usable_by: ~s(Corvette), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Bolt Guns E`C!), description: ~s(L Bolt Guns fire high velocity kinetic impactors with a long effective range. 551 /Game/Generic/UI/weapons/UI_weapon_2.UI_weapon_2 G_H!"?`8!), slot: ~s(Secondary Weapon), usable_by: ~s(Corvette), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Plasma Turrets HeC!), description: ~s(l Plasma Turrets are optimized for medium range encounters and offer high rates of fire with moderate damage. 773 /Game/Generic/UI/weapons/UI_weapon_21.UI_weapon_21 JdK"#@e8!), slot: ~s(Secondary Weapon), usable_by: ~s(Corvette), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Beam Turrets LjC!), description: ~s(1 Beam Turrets deal high damage at limited ranges. >51 /Game/Generic/UI/weapons/UI_weapon_1.UI_weapon_1 NiO%&Ij8!), slot: ~s(Secondary Weapon), usable_by: ~s(Corvette), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Heavy Particle Cannon FbA!), description: ~s(x Heavy Particle Cannon deals massive damage to extreme ranges with high accuracy, but features a very slow rate of fire. 573 /Game/Generic/UI/weapons/UI_weapon_10.UI_weapon_10 HaI"#@b8!), slot: ~s(Primary Weapon), usable_by: ~s(Artillery Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Particle Turrets ?YA!), description: ~s(S Medium Particle Turrets offer a fast rate of fire with a moderate damage per shot. 373 /Game/Generic/UI/weapons/UI_weapon_19.UI_weapon_19 AXB  !:Y8!), slot: ~s(Primary Weapon), usable_by: ~s(Artillery Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Heavy Tesla Cannon RyA!), description: ~s(g Heavy Tesla Cannon deals high damage at long ranges with high accuracy, but features a slow fire rate. B73 /Game/Generic/UI/weapons/UI_weapon_13.UI_weapon_13 TwU*+My8!), slot: ~s(Primary Weapon), usable_by: ~s(Artillery Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Bolt Gun Turrets EaC!), description: ~s(S Bolt Gun Turrets fire high velocity kinetic impactors with a long effective range. 351 /Game/Generic/UI/weapons/UI_weapon_3.UI_weapon_3 G`H  !=a8!), slot: ~s(Secondary Weapon), usable_by: ~s(Artillery Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Machine Gun Turrets D`C!), description: ~s(Z Machine Gun Turrets offer moderate rates of fire and damage against medium range targets. 373 /Game/Generic/UI/weapons/UI_weapon_28.UI_weapon_28 F_G  !<`8!), slot: ~s(Secondary Weapon), usable_by: ~s(Artillery Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Light Flak Turrets EbC!), description: ~s(v Light Flak Turrets unleash high explosive shells at high rates of fire and are excellent for engaging close targets, 673 /Game/Generic/UI/weapons/UI_weapon_14.UI_weapon_14 GaH!"?b8!), slot: ~s(Secondary Weapon), usable_by: ~s(Artillery Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Heavy Repair Beam VwA!), description: ~s(n Heavy Repair Beam Turrets feature no offensive capabilities, but are invaluable for repairing allied vessels. B73 /Game/Generic/UI/weapons/UI_weapon_12.UI_weapon_12 XuY!*+Qw8!), slot: ~s(Primary Weapon), usable_by: ~s(Tactical Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Heavy Beam Turrets XzA!), description: ~s(m Heavy Beam Turrets can be deal significant damage to enemies at long ranges, but cannot be used for repairs. C51 /Game/Generic/UI/weapons/UI_weapon_7.UI_weapon_7 Zx), slot: ~s(Primary Weapon), usable_by: ~s(Tactical Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Medium Beam Turrets XxA!), description: ~s(g Medium Beam Turrets can be used to both repair allies and damage enemies, but with limited efficiency. C73 /Game/Generic/UI/weapons/UI_weapon_18.UI_weapon_18 Zv["+,Sx8!), slot: ~s(Primary Weapon), usable_by: ~s(Tactical Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Light Rocket Turrets B\C!), description: ~s(d Light Rocket Turrets fire volleys of light rockets to mid to close ranges, dealing moderate damage. 373 /Game/Generic/UI/weapons/UI_weapon_15.UI_weapon_15 DZE!":\8!), slot: ~s(Secondary Weapon), usable_by: ~s(Tactical Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Light Machine Guns SwC!), description: ~s(n Light Machine Gun Turrets feature limited damage output, but come with high rates of fire and moderate range. C73 /Game/Generic/UI/weapons/UI_weapon_17.UI_weapon_17 UuV), slot: ~s(Secondary Weapon), usable_by: ~s(Tactical Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

Repo.insert!(%Weapon{name: ~s(Tesla Turrets IfC!), description: ~s(c High damage, short range electric beams, optimally used to fight off smaller, close range targets. =73 /Game/Generic/UI/weapons/UI_weapon_25.UI_weapon_25 KdL$%Ff8!), slot: ~s(Secondary Weapon), usable_by: ~s(Tactical Cruiser), unlock_level: 1337, cr: 1337, sp: 1337, shots: 1337, reload_time: 1337, icon_uri: ~s(derp), raw_json: %{:placeholder => true}})

